<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (TGL?,KD_PAT?,KD_SBU?,RKAP?,RI_PEROLEHAN?,RI_PERSEN?,RI_WIKA?,RI_PEMERINTAH?,RI_BUMN?,RI_SWASTA?,RI_JML_NON_WIKA?,LAST_UPDATE_DATE?)+>
  <!ELEMENT TGL (#PCDATA)>
  <!ELEMENT KD_PAT (#PCDATA)>
  <!ELEMENT KD_SBU (#PCDATA)>
  <!ELEMENT RKAP (#PCDATA)>
  <!ELEMENT RI_PEROLEHAN (#PCDATA)>
  <!ELEMENT RI_PERSEN (#PCDATA)>
  <!ELEMENT RI_WIKA (#PCDATA)>
  <!ELEMENT RI_PEMERINTAH (#PCDATA)>
  <!ELEMENT RI_BUMN (#PCDATA)>
  <!ELEMENT RI_SWASTA (#PCDATA)>
  <!ELEMENT RI_JML_NON_WIKA (#PCDATA)>
  <!ELEMENT LAST_UPDATE_DATE (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1A</KD_PAT>
    <KD_SBU>A</KD_SBU>
    <RKAP>14340000000</RKAP>
    <RI_PEROLEHAN>11715266987</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>7873928487</RI_PEMERINTAH>
    <RI_BUMN>193350000</RI_BUMN>
    <RI_SWASTA>3647988500</RI_SWASTA>
    <RI_JML_NON_WIKA>11715266987</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1A</KD_PAT>
    <KD_SBU>B</KD_SBU>
    <RKAP>206949000000</RKAP>
    <RI_PEROLEHAN>283054466380</RI_PEROLEHAN>
    <RI_WIKA>2134539000</RI_WIKA>
    <RI_PEMERINTAH>2609696600</RI_PEMERINTAH>
    <RI_BUMN>28718926600</RI_BUMN>
    <RI_SWASTA>249591304180</RI_SWASTA>
    <RI_JML_NON_WIKA>280919927380</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1A</KD_PAT>
    <KD_SBU>C</KD_SBU>
    <RKAP>19443000000</RKAP>
    <RI_PEROLEHAN>23671037050</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>21548465800</RI_PEMERINTAH>
    <RI_BUMN>2122571250</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>23671037050</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1A</KD_PAT>
    <KD_SBU>D</KD_SBU>
    <RKAP>11433000000</RKAP>
    <RI_PEROLEHAN>15409653150</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>2052675000</RI_PEMERINTAH>
    <RI_BUMN>6987280000</RI_BUMN>
    <RI_SWASTA>6369698150</RI_SWASTA>
    <RI_JML_NON_WIKA>15409653150</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1A</KD_PAT>
    <KD_SBU>E</KD_SBU>
    <RKAP>33006000000</RKAP>
    <RI_PEROLEHAN>25241660000</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>2754000000</RI_PEMERINTAH>
    <RI_BUMN>4016612000</RI_BUMN>
    <RI_SWASTA>18471048000</RI_SWASTA>
    <RI_JML_NON_WIKA>25241660000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1A</KD_PAT>
    <KD_SBU>F</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1A</KD_PAT>
    <KD_SBU>G</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1A</KD_PAT>
    <KD_SBU>H</KD_SBU>
    <RKAP>15000000000</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1A</KD_PAT>
    <KD_SBU>I</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1A</KD_PAT>
    <KD_SBU>J</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>385420000</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>90000000</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>295420000</RI_SWASTA>
    <RI_JML_NON_WIKA>385420000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1B</KD_PAT>
    <KD_SBU>A</KD_SBU>
    <RKAP>73500000000</RKAP>
    <RI_PEROLEHAN>72449465900</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>56092901000</RI_PEMERINTAH>
    <RI_BUMN>12831314000</RI_BUMN>
    <RI_SWASTA>3525250900</RI_SWASTA>
    <RI_JML_NON_WIKA>72449465900</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1B</KD_PAT>
    <KD_SBU>B</KD_SBU>
    <RKAP>59800000000</RKAP>
    <RI_PEROLEHAN>82080709656</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>11362287240</RI_BUMN>
    <RI_SWASTA>70718422416</RI_SWASTA>
    <RI_JML_NON_WIKA>82080709656</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1B</KD_PAT>
    <KD_SBU>C</KD_SBU>
    <RKAP>28800000000</RKAP>
    <RI_PEROLEHAN>43369583000</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>37565703000</RI_BUMN>
    <RI_SWASTA>5803880000</RI_SWASTA>
    <RI_JML_NON_WIKA>43369583000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1B</KD_PAT>
    <KD_SBU>D</KD_SBU>
    <RKAP>20900000000</RKAP>
    <RI_PEROLEHAN>28139767250</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>11084379550</RI_BUMN>
    <RI_SWASTA>17055387700</RI_SWASTA>
    <RI_JML_NON_WIKA>28139767250</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1B</KD_PAT>
    <KD_SBU>E</KD_SBU>
    <RKAP>10500000000</RKAP>
    <RI_PEROLEHAN>7412592000</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>7412592000</RI_SWASTA>
    <RI_JML_NON_WIKA>7412592000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1B</KD_PAT>
    <KD_SBU>F</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1B</KD_PAT>
    <KD_SBU>G</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1B</KD_PAT>
    <KD_SBU>H</KD_SBU>
    <RKAP>4500000000</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1B</KD_PAT>
    <KD_SBU>I</KD_SBU>
    <RKAP>2000000000</RKAP>
    <RI_PEROLEHAN>1635000000</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>1635000000</RI_SWASTA>
    <RI_JML_NON_WIKA>1635000000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1B</KD_PAT>
    <KD_SBU>J</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1C</KD_PAT>
    <KD_SBU>A</KD_SBU>
    <RKAP>28666009500</RKAP>
    <RI_PEROLEHAN>34269519200</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>13362966000</RI_PEMERINTAH>
    <RI_BUMN>5958908000</RI_BUMN>
    <RI_SWASTA>14947645200</RI_SWASTA>
    <RI_JML_NON_WIKA>34269519200</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1C</KD_PAT>
    <KD_SBU>B</KD_SBU>
    <RKAP>254917508630</RKAP>
    <RI_PEROLEHAN>329509117287</RI_PEROLEHAN>
    <RI_WIKA>31558754120</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>94729617140</RI_BUMN>
    <RI_SWASTA>203220746027</RI_SWASTA>
    <RI_JML_NON_WIKA>297950363167</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1C</KD_PAT>
    <KD_SBU>C</KD_SBU>
    <RKAP>29240000000</RKAP>
    <RI_PEROLEHAN>45294014140</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>29083271500</RI_BUMN>
    <RI_SWASTA>16210742640</RI_SWASTA>
    <RI_JML_NON_WIKA>45294014140</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1C</KD_PAT>
    <KD_SBU>D</KD_SBU>
    <RKAP>272970320295</RKAP>
    <RI_PEROLEHAN>63956142950</RI_PEROLEHAN>
    <RI_WIKA>14470706200</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>39700058750</RI_BUMN>
    <RI_SWASTA>9785378000</RI_SWASTA>
    <RI_JML_NON_WIKA>49485436750</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1C</KD_PAT>
    <KD_SBU>E</KD_SBU>
    <RKAP>91730112160</RKAP>
    <RI_PEROLEHAN>110480867000</RI_PEROLEHAN>
    <RI_WIKA>41939940000</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>35137315000</RI_BUMN>
    <RI_SWASTA>33403612000</RI_SWASTA>
    <RI_JML_NON_WIKA>68540927000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1C</KD_PAT>
    <KD_SBU>F</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1C</KD_PAT>
    <KD_SBU>G</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1C</KD_PAT>
    <KD_SBU>H</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>5137117100</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>5137117100</RI_SWASTA>
    <RI_JML_NON_WIKA>5137117100</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1C</KD_PAT>
    <KD_SBU>I</KD_SBU>
    <RKAP>22500050000</RKAP>
    <RI_PEROLEHAN>10702308652</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>10702308652</RI_SWASTA>
    <RI_JML_NON_WIKA>10702308652</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1C</KD_PAT>
    <KD_SBU>J</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>4010052000</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>3137732000</RI_BUMN>
    <RI_SWASTA>872320000</RI_SWASTA>
    <RI_JML_NON_WIKA>4010052000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:48</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1D</KD_PAT>
    <KD_SBU>A</KD_SBU>
    <RKAP>22530003615</RKAP>
    <RI_PEROLEHAN>30490694028</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>20935602028</RI_BUMN>
    <RI_SWASTA>9555092000</RI_SWASTA>
    <RI_JML_NON_WIKA>30490694028</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1D</KD_PAT>
    <KD_SBU>B</KD_SBU>
    <RKAP>115941002883</RKAP>
    <RI_PEROLEHAN>138419452744</RI_PEROLEHAN>
    <RI_WIKA>23872982200</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>27670776300</RI_BUMN>
    <RI_SWASTA>86875694244</RI_SWASTA>
    <RI_JML_NON_WIKA>114546470544</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1D</KD_PAT>
    <KD_SBU>C</KD_SBU>
    <RKAP>136620000000</RKAP>
    <RI_PEROLEHAN>86012308500</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>35246718500</RI_PEMERINTAH>
    <RI_BUMN>50750100000</RI_BUMN>
    <RI_SWASTA>15490000</RI_SWASTA>
    <RI_JML_NON_WIKA>86012308500</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1D</KD_PAT>
    <KD_SBU>D</KD_SBU>
    <RKAP>31125000038</RKAP>
    <RI_PEROLEHAN>44849133959</RI_PEROLEHAN>
    <RI_WIKA>1237500000</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>1933657740</RI_BUMN>
    <RI_SWASTA>41677976219</RI_SWASTA>
    <RI_JML_NON_WIKA>43611633959</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1D</KD_PAT>
    <KD_SBU>E</KD_SBU>
    <RKAP>10800000450</RKAP>
    <RI_PEROLEHAN>24049653400</RI_PEROLEHAN>
    <RI_WIKA>280600000</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>2270760000</RI_BUMN>
    <RI_SWASTA>21498293400</RI_SWASTA>
    <RI_JML_NON_WIKA>23769053400</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1D</KD_PAT>
    <KD_SBU>F</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1D</KD_PAT>
    <KD_SBU>G</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1D</KD_PAT>
    <KD_SBU>H</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>2090725000</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>2090725000</RI_SWASTA>
    <RI_JML_NON_WIKA>2090725000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1D</KD_PAT>
    <KD_SBU>I</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>122793328900</RI_PEROLEHAN>
    <RI_WIKA>9116500000</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>478850000</RI_BUMN>
    <RI_SWASTA>113197978900</RI_SWASTA>
    <RI_JML_NON_WIKA>113676828900</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1D</KD_PAT>
    <KD_SBU>J</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>9239321024</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>223117260</RI_BUMN>
    <RI_SWASTA>9016203764</RI_SWASTA>
    <RI_JML_NON_WIKA>9239321024</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1E</KD_PAT>
    <KD_SBU>A</KD_SBU>
    <RKAP>27718300000</RKAP>
    <RI_PEROLEHAN>25617461500</RI_PEROLEHAN>
    <RI_WIKA>155100000</RI_WIKA>
    <RI_PEMERINTAH>4006084500</RI_PEMERINTAH>
    <RI_BUMN>8065730000</RI_BUMN>
    <RI_SWASTA>13390547000</RI_SWASTA>
    <RI_JML_NON_WIKA>25462361500</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1E</KD_PAT>
    <KD_SBU>B</KD_SBU>
    <RKAP>217004099784</RKAP>
    <RI_PEROLEHAN>339955174648</RI_PEROLEHAN>
    <RI_WIKA>17571668100</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>80129347300</RI_BUMN>
    <RI_SWASTA>242254159248</RI_SWASTA>
    <RI_JML_NON_WIKA>322383506548</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1E</KD_PAT>
    <KD_SBU>C</KD_SBU>
    <RKAP>50120600000</RKAP>
    <RI_PEROLEHAN>111751618000</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>99101150000</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>12650468000</RI_SWASTA>
    <RI_JML_NON_WIKA>111751618000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1E</KD_PAT>
    <KD_SBU>D</KD_SBU>
    <RKAP>144881000000</RKAP>
    <RI_PEROLEHAN>41982088600</RI_PEROLEHAN>
    <RI_WIKA>2547950000</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>7134885000</RI_BUMN>
    <RI_SWASTA>32299253600</RI_SWASTA>
    <RI_JML_NON_WIKA>39434138600</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1E</KD_PAT>
    <KD_SBU>E</KD_SBU>
    <RKAP>86786000226</RKAP>
    <RI_PEROLEHAN>19695260000</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>926640000</RI_BUMN>
    <RI_SWASTA>18768620000</RI_SWASTA>
    <RI_JML_NON_WIKA>19695260000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1E</KD_PAT>
    <KD_SBU>F</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1E</KD_PAT>
    <KD_SBU>G</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1E</KD_PAT>
    <KD_SBU>H</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1E</KD_PAT>
    <KD_SBU>I</KD_SBU>
    <RKAP>23490000000</RKAP>
    <RI_PEROLEHAN>23822370000</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>23822370000</RI_SWASTA>
    <RI_JML_NON_WIKA>23822370000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1E</KD_PAT>
    <KD_SBU>J</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>2302300000</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>593900000</RI_BUMN>
    <RI_SWASTA>1708400000</RI_SWASTA>
    <RI_JML_NON_WIKA>2302300000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1F</KD_PAT>
    <KD_SBU>A</KD_SBU>
    <RKAP>53300220000</RKAP>
    <RI_PEROLEHAN>47823408009</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>43044108009</RI_BUMN>
    <RI_SWASTA>4779300000</RI_SWASTA>
    <RI_JML_NON_WIKA>47823408009</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1F</KD_PAT>
    <KD_SBU>B</KD_SBU>
    <RKAP>81699881000</RKAP>
    <RI_PEROLEHAN>93773036523</RI_PEROLEHAN>
    <RI_WIKA>5753450120</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>30535648473</RI_BUMN>
    <RI_SWASTA>57483937930</RI_SWASTA>
    <RI_JML_NON_WIKA>88019586403</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1F</KD_PAT>
    <KD_SBU>C</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1F</KD_PAT>
    <KD_SBU>D</KD_SBU>
    <RKAP>53089500000</RKAP>
    <RI_PEROLEHAN>18127372000</RI_PEROLEHAN>
    <RI_WIKA>5820268000</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>3862400000</RI_BUMN>
    <RI_SWASTA>8444704000</RI_SWASTA>
    <RI_JML_NON_WIKA>12307104000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1F</KD_PAT>
    <KD_SBU>E</KD_SBU>
    <RKAP>18800400000</RKAP>
    <RI_PEROLEHAN>16327350000</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>5168850000</RI_BUMN>
    <RI_SWASTA>11158500000</RI_SWASTA>
    <RI_JML_NON_WIKA>16327350000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1F</KD_PAT>
    <KD_SBU>F</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1F</KD_PAT>
    <KD_SBU>G</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1F</KD_PAT>
    <KD_SBU>H</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1F</KD_PAT>
    <KD_SBU>I</KD_SBU>
    <RKAP>8110000000</RKAP>
    <RI_PEROLEHAN>434500000</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>434500000</RI_SWASTA>
    <RI_JML_NON_WIKA>434500000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>1F</KD_PAT>
    <KD_SBU>J</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>5529400000</RI_PEROLEHAN>
    <RI_WIKA>1527750000</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>877600000</RI_BUMN>
    <RI_SWASTA>3124050000</RI_SWASTA>
    <RI_JML_NON_WIKA>4001650000</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>WB</KD_PAT>
    <KD_SBU>A</KD_SBU>
    <RKAP>220054533115</RKAP>
    <RI_PEROLEHAN>222365815624</RI_PEROLEHAN>
    <RI_WIKA>155100000</RI_WIKA>
    <RI_PEMERINTAH>81335879987</RI_PEMERINTAH>
    <RI_BUMN>91029012037</RI_BUMN>
    <RI_SWASTA>49845823600</RI_SWASTA>
    <RI_JML_NON_WIKA>222210715624</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>WB</KD_PAT>
    <KD_SBU>B</KD_SBU>
    <RKAP>936311492297</RKAP>
    <RI_PEROLEHAN>1266791957238</RI_PEROLEHAN>
    <RI_WIKA>80891393540</RI_WIKA>
    <RI_PEMERINTAH>2609696600</RI_PEMERINTAH>
    <RI_BUMN>273146603053</RI_BUMN>
    <RI_SWASTA>910144264045</RI_SWASTA>
    <RI_JML_NON_WIKA>1185900563698</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>WB</KD_PAT>
    <KD_SBU>C</KD_SBU>
    <RKAP>264223600000</RKAP>
    <RI_PEROLEHAN>310098560690</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>155896334300</RI_PEMERINTAH>
    <RI_BUMN>119521645750</RI_BUMN>
    <RI_SWASTA>34680580640</RI_SWASTA>
    <RI_JML_NON_WIKA>310098560690</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>WB</KD_PAT>
    <KD_SBU>D</KD_SBU>
    <RKAP>534398820333</RKAP>
    <RI_PEROLEHAN>212464157909</RI_PEROLEHAN>
    <RI_WIKA>24076424200</RI_WIKA>
    <RI_PEMERINTAH>2052675000</RI_PEMERINTAH>
    <RI_BUMN>70702661040</RI_BUMN>
    <RI_SWASTA>115632397669</RI_SWASTA>
    <RI_JML_NON_WIKA>188387733709</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>WB</KD_PAT>
    <KD_SBU>E</KD_SBU>
    <RKAP>251622512836</RKAP>
    <RI_PEROLEHAN>203207382400</RI_PEROLEHAN>
    <RI_WIKA>42220540000</RI_WIKA>
    <RI_PEMERINTAH>2754000000</RI_PEMERINTAH>
    <RI_BUMN>47520177000</RI_BUMN>
    <RI_SWASTA>110712665400</RI_SWASTA>
    <RI_JML_NON_WIKA>160986842400</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>WB</KD_PAT>
    <KD_SBU>F</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>WB</KD_PAT>
    <KD_SBU>G</KD_SBU>
    <RKAP>0</RKAP>
    <RI_PEROLEHAN>0</RI_PEROLEHAN>
    <RI_WIKA>0</RI_WIKA>
    <RI_PEMERINTAH>0</RI_PEMERINTAH>
    <RI_BUMN>0</RI_BUMN>
    <RI_SWASTA>0</RI_SWASTA>
    <RI_JML_NON_WIKA>0</RI_JML_NON_WIKA>
    <LAST_UPDATE_DATE>2012/11/23 22:46:49</LAST_UPDATE_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TGL>2012/11/23 00:00:00</TGL>
    <KD_PAT>WB</KD_PAT>
    <KD_SBU>H</KD_SBU>