<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (KD_PAT,KET?,KD_SBU,KET_SBU?,OP?)+>
  <!ELEMENT KD_PAT (#PCDATA)>
  <!ELEMENT KET (#PCDATA)>
  <!ELEMENT KD_SBU (#PCDATA)>
  <!ELEMENT KET_SBU (#PCDATA)>
  <!ELEMENT OP (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <KD_PAT>1A</KD_PAT>
    <KET>Wilayah Penjualan I</KET>
    <KD_SBU>A</KD_SBU>
    <KET_SBU>TIANG BETON &#40; PC POLES &#41;</KET_SBU>
    <OP>7093792437</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1A</KD_PAT>
    <KET>Wilayah Penjualan I</KET>
    <KD_SBU>B</KD_SBU>
    <KET_SBU>TIANG PANCANG &#40; PC PILES &#41;</KET_SBU>
    <OP>90287340085</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1A</KD_PAT>
    <KET>Wilayah Penjualan I</KET>
    <KD_SBU>C</KD_SBU>
    <KET_SBU>PRODUK BETON JALAN REL &#40;RAILWAY CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1A</KD_PAT>
    <KET>Wilayah Penjualan I</KET>
    <KD_SBU>D</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK JEMBATAN &#40;BRIDGE CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1A</KD_PAT>
    <KET>Wilayah Penjualan I</KET>
    <KD_SBU>E</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK DINDING PENAHAN TANAH &#40;RETAINING WALL CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>7963178000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1A</KD_PAT>
    <KET>Wilayah Penjualan I</KET>
    <KD_SBU>F</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN AIR &#40;HYDRO STRUCTURE CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1A</KD_PAT>
    <KET>Wilayah Penjualan I</KET>
    <KD_SBU>G</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN GEDUNG DAN PERUMAHAN &#40;BOULDING &#38; HOUSING CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1A</KD_PAT>
    <KET>Wilayah Penjualan I</KET>
    <KD_SBU>H</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN MARITIM &#40;MARINE STRUCTURE CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1A</KD_PAT>
    <KET>Wilayah Penjualan I</KET>
    <KD_SBU>I</KD_SBU>
    <KET_SBU>PRODUK BETON LAIN - LAIN &#40;OTHERS CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1A</KD_PAT>
    <KET>Wilayah Penjualan I</KET>
    <KD_SBU>J</KD_SBU>
    <KET_SBU>JASA &#40;SERVICES&#41;</KET_SBU>
    <OP>12480000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1B</KD_PAT>
    <KET>Wilayah Penjualan II</KET>
    <KD_SBU>A</KD_SBU>
    <KET_SBU>TIANG BETON &#40; PC POLES &#41;</KET_SBU>
    <OP>20353376900</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1B</KD_PAT>
    <KET>Wilayah Penjualan II</KET>
    <KD_SBU>B</KD_SBU>
    <KET_SBU>TIANG PANCANG &#40; PC PILES &#41;</KET_SBU>
    <OP>20438544591</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1B</KD_PAT>
    <KET>Wilayah Penjualan II</KET>
    <KD_SBU>C</KD_SBU>
    <KET_SBU>PRODUK BETON JALAN REL &#40;RAILWAY CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>1326920000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1B</KD_PAT>
    <KET>Wilayah Penjualan II</KET>
    <KD_SBU>D</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK JEMBATAN &#40;BRIDGE CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>2457165750</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1B</KD_PAT>
    <KET>Wilayah Penjualan II</KET>
    <KD_SBU>E</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK DINDING PENAHAN TANAH &#40;RETAINING WALL CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>3540360000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1B</KD_PAT>
    <KET>Wilayah Penjualan II</KET>
    <KD_SBU>F</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN AIR &#40;HYDRO STRUCTURE CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1B</KD_PAT>
    <KET>Wilayah Penjualan II</KET>
    <KD_SBU>G</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN GEDUNG DAN PERUMAHAN &#40;BOULDING &#38; HOUSING CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1B</KD_PAT>
    <KET>Wilayah Penjualan II</KET>
    <KD_SBU>H</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN MARITIM &#40;MARINE STRUCTURE CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1B</KD_PAT>
    <KET>Wilayah Penjualan II</KET>
    <KD_SBU>I</KD_SBU>
    <KET_SBU>PRODUK BETON LAIN - LAIN &#40;OTHERS CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1B</KD_PAT>
    <KET>Wilayah Penjualan II</KET>
    <KD_SBU>J</KD_SBU>
    <KET_SBU>JASA &#40;SERVICES&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1C</KD_PAT>
    <KET>Wilayah Penjualan III</KET>
    <KD_SBU>A</KD_SBU>
    <KET_SBU>TIANG BETON &#40; PC POLES &#41;</KET_SBU>
    <OP>15811436000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1C</KD_PAT>
    <KET>Wilayah Penjualan III</KET>
    <KD_SBU>B</KD_SBU>
    <KET_SBU>TIANG PANCANG &#40; PC PILES &#41;</KET_SBU>
    <OP>92684526434</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1C</KD_PAT>
    <KET>Wilayah Penjualan III</KET>
    <KD_SBU>C</KD_SBU>
    <KET_SBU>PRODUK BETON JALAN REL &#40;RAILWAY CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>21234761500</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1C</KD_PAT>
    <KET>Wilayah Penjualan III</KET>
    <KD_SBU>D</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK JEMBATAN &#40;BRIDGE CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>24835467950</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1C</KD_PAT>
    <KET>Wilayah Penjualan III</KET>
    <KD_SBU>E</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK DINDING PENAHAN TANAH &#40;RETAINING WALL CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>58427963000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1C</KD_PAT>
    <KET>Wilayah Penjualan III</KET>
    <KD_SBU>F</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN AIR &#40;HYDRO STRUCTURE CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1C</KD_PAT>
    <KET>Wilayah Penjualan III</KET>
    <KD_SBU>G</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN GEDUNG DAN PERUMAHAN &#40;BOULDING &#38; HOUSING CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1C</KD_PAT>
    <KET>Wilayah Penjualan III</KET>
    <KD_SBU>H</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN MARITIM &#40;MARINE STRUCTURE CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>1092244500</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1C</KD_PAT>
    <KET>Wilayah Penjualan III</KET>
    <KD_SBU>I</KD_SBU>
    <KET_SBU>PRODUK BETON LAIN - LAIN &#40;OTHERS CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>120000000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1C</KD_PAT>
    <KET>Wilayah Penjualan III</KET>
    <KD_SBU>J</KD_SBU>
    <KET_SBU>JASA &#40;SERVICES&#41;</KET_SBU>
    <OP>870320000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1D</KD_PAT>
    <KET>Wilayah Penjualan IV</KET>
    <KD_SBU>A</KD_SBU>
    <KET_SBU>TIANG BETON &#40; PC POLES &#41;</KET_SBU>
    <OP>18064253028</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1D</KD_PAT>
    <KET>Wilayah Penjualan IV</KET>
    <KD_SBU>B</KD_SBU>
    <KET_SBU>TIANG PANCANG &#40; PC PILES &#41;</KET_SBU>
    <OP>79889583869</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1D</KD_PAT>
    <KET>Wilayah Penjualan IV</KET>
    <KD_SBU>C</KD_SBU>
    <KET_SBU>PRODUK BETON JALAN REL &#40;RAILWAY CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>5250000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1D</KD_PAT>
    <KET>Wilayah Penjualan IV</KET>
    <KD_SBU>D</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK JEMBATAN &#40;BRIDGE CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>2176237344</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1D</KD_PAT>
    <KET>Wilayah Penjualan IV</KET>
    <KD_SBU>E</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK DINDING PENAHAN TANAH &#40;RETAINING WALL CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>13455938400</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1D</KD_PAT>
    <KET>Wilayah Penjualan IV</KET>
    <KD_SBU>F</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN AIR &#40;HYDRO STRUCTURE CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1D</KD_PAT>
    <KET>Wilayah Penjualan IV</KET>
    <KD_SBU>G</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN GEDUNG DAN PERUMAHAN &#40;BOULDING &#38; HOUSING CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1D</KD_PAT>
    <KET>Wilayah Penjualan IV</KET>
    <KD_SBU>H</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN MARITIM &#40;MARINE STRUCTURE CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>2090725000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1D</KD_PAT>
    <KET>Wilayah Penjualan IV</KET>
    <KD_SBU>I</KD_SBU>
    <KET_SBU>PRODUK BETON LAIN - LAIN &#40;OTHERS CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>1008400000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1D</KD_PAT>
    <KET>Wilayah Penjualan IV</KET>
    <KD_SBU>J</KD_SBU>
    <KET_SBU>JASA &#40;SERVICES&#41;</KET_SBU>
    <OP>112162656</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1E</KD_PAT>
    <KET>Wilayah Penjualan V</KET>
    <KD_SBU>A</KD_SBU>
    <KET_SBU>TIANG BETON &#40; PC POLES &#41;</KET_SBU>
    <OP>11820726000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1E</KD_PAT>
    <KET>Wilayah Penjualan V</KET>
    <KD_SBU>B</KD_SBU>
    <KET_SBU>TIANG PANCANG &#40; PC PILES &#41;</KET_SBU>
    <OP>107028269895</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1E</KD_PAT>
    <KET>Wilayah Penjualan V</KET>
    <KD_SBU>C</KD_SBU>
    <KET_SBU>PRODUK BETON JALAN REL &#40;RAILWAY CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>1739720000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1E</KD_PAT>
    <KET>Wilayah Penjualan V</KET>
    <KD_SBU>D</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK JEMBATAN &#40;BRIDGE CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>3446671350</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1E</KD_PAT>
    <KET>Wilayah Penjualan V</KET>
    <KD_SBU>E</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK DINDING PENAHAN TANAH &#40;RETAINING WALL CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>1724670000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1E</KD_PAT>
    <KET>Wilayah Penjualan V</KET>
    <KD_SBU>F</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN AIR &#40;HYDRO STRUCTURE CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1E</KD_PAT>
    <KET>Wilayah Penjualan V</KET>
    <KD_SBU>G</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN GEDUNG DAN PERUMAHAN &#40;BOULDING &#38; HOUSING CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1E</KD_PAT>
    <KET>Wilayah Penjualan V</KET>
    <KD_SBU>H</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN MARITIM &#40;MARINE STRUCTURE CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1E</KD_PAT>
    <KET>Wilayah Penjualan V</KET>
    <KD_SBU>I</KD_SBU>
    <KET_SBU>PRODUK BETON LAIN - LAIN &#40;OTHERS CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>4752000000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1E</KD_PAT>
    <KET>Wilayah Penjualan V</KET>
    <KD_SBU>J</KD_SBU>
    <KET_SBU>JASA &#40;SERVICES&#41;</KET_SBU>
    <OP>104300000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1F</KD_PAT>
    <KET>Wilayah Penjualan VI</KET>
    <KD_SBU>A</KD_SBU>
    <KET_SBU>TIANG BETON &#40; PC POLES &#41;</KET_SBU>
    <OP>12642405009,35</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1F</KD_PAT>
    <KET>Wilayah Penjualan VI</KET>
    <KD_SBU>B</KD_SBU>
    <KET_SBU>TIANG PANCANG &#40; PC PILES &#41;</KET_SBU>
    <OP>17115496415</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1F</KD_PAT>
    <KET>Wilayah Penjualan VI</KET>
    <KD_SBU>C</KD_SBU>
    <KET_SBU>PRODUK BETON JALAN REL &#40;RAILWAY CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1F</KD_PAT>
    <KET>Wilayah Penjualan VI</KET>
    <KD_SBU>D</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK JEMBATAN &#40;BRIDGE CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>3222235000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1F</KD_PAT>
    <KET>Wilayah Penjualan VI</KET>
    <KD_SBU>E</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK DINDING PENAHAN TANAH &#40;RETAINING WALL CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>985320000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1F</KD_PAT>
    <KET>Wilayah Penjualan VI</KET>
    <KD_SBU>F</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN AIR &#40;HYDRO STRUCTURE CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1F</KD_PAT>
    <KET>Wilayah Penjualan VI</KET>
    <KD_SBU>G</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN GEDUNG DAN PERUMAHAN &#40;BOULDING &#38; HOUSING CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1F</KD_PAT>
    <KET>Wilayah Penjualan VI</KET>
    <KD_SBU>H</KD_SBU>
    <KET_SBU>PRODUK BETON UNTUK BANGUNAN MARITIM &#40;MARINE STRUCTURE CONCRETE PRODUCTS&#41;</KET_SBU>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1F</KD_PAT>
    <KET>Wilayah Penjualan VI</KET>
    <KD_SBU>I</KD_SBU>
    <KET_SBU>PRODUK BETON LAIN - LAIN &#40;OTHERS CONCRETE PRODUCTS&#41;</KET_SBU>
    <OP>434500000</OP>
  </DATA_RECORD>
  <DATA_RECORD>
    <KD_PAT>1F</KD_PAT>
    <KET>Wilayah Penjualan VI</KET>
    <KD_SBU>J</KD_SBU>
    <KET_SBU>JASA &#40;SERVICES&#41;</KET_SBU>
    <OP>1004500000</OP>
  </DATA_RECORD>
</main>
